// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_mCM0Y6iidsvATUgPJapeTw3A7d9KNbs',
    appId: '1:55231876574:web:f4a07190c94926a107214f',
    messagingSenderId: '55231876574',
    projectId: 'car-help-2786d',
    authDomain: 'car-help-2786d.firebaseapp.com',
    storageBucket: 'car-help-2786d.appspot.com',
    measurementId: 'G-MLMT889TH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZTpQHONmurXHghNr7SasB0QhGbiIrLfA',
    appId: '1:55231876574:android:868887b25fc5860407214f',
    messagingSenderId: '55231876574',
    projectId: 'car-help-2786d',
    storageBucket: 'car-help-2786d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYtEM60vmLOVlet9SLZAxMDYadOVEypr0',
    appId: '1:55231876574:ios:79187a2174ba7e9707214f',
    messagingSenderId: '55231876574',
    projectId: 'car-help-2786d',
    storageBucket: 'car-help-2786d.appspot.com',
    iosBundleId: 'com.example.carHelpApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYtEM60vmLOVlet9SLZAxMDYadOVEypr0',
    appId: '1:55231876574:ios:79187a2174ba7e9707214f',
    messagingSenderId: '55231876574',
    projectId: 'car-help-2786d',
    storageBucket: 'car-help-2786d.appspot.com',
    iosBundleId: 'com.example.carHelpApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_mCM0Y6iidsvATUgPJapeTw3A7d9KNbs',
    appId: '1:55231876574:web:e4f754eed48714af07214f',
    messagingSenderId: '55231876574',
    projectId: 'car-help-2786d',
    authDomain: 'car-help-2786d.firebaseapp.com',
    storageBucket: 'car-help-2786d.appspot.com',
    measurementId: 'G-PCM7KD6TV3',
  );
}
